.PHONY: all cleansub
all:
	mkpsxiso -y ./isoconfig.xml
cleansub:
	$(MAKE) clean
	rm -f fnaf3.cue fnaf3.bin

TARGET = fnaf3

SRCS = fnaf3.c \
tim/gameover/GAMEOVER.tim \
tim/office/springtraphide/1.tim \
tim/office/springtraphide/2.tim \
tim/office/springtraphide/3.tim \
tim/office/springtraphide/4.tim \
tim/office/springtraphide/5.tim \
tim/office/springtraphide/6.tim \
tim/office/springtraphide/7.tim \
tim/office/springtraphide/8.tim \
tim/office/springtraphide/9.tim \
tim/office/springtraphide/10.tim \
tim/office/springtraphide/11.tim \
tim/office/mutecall.tim \
tim/office/fan/FAN0.tim \
tim/office/fan/FAN1.tim \
tim/office/fan/FAN2.tim \
tim/office/animatronics/springtrap/SPRINGTRAP1.tim \
tim/office/animatronics/springtrap/SPRINGTRAP2.tim \
tim/office/animatronics/springtrap/SPRINGTRAPOFFICELEAVING1.tim \
tim/office/animatronics/springtrap/SPRINGTRAPOFFICELEAVING2.tim \
tim/office/animatronics/springtrap/SPRINGTRAPOFFICELEAVING3.tim \
tim/office/animatronics/springtrap/SPRINGTRAPOFFICELEAVING4.tim \
tim/office/animatronics/springtrap/SPRINGTRAPOFFICELEAVING5.tim \
tim/office/animatronics/springtrap/SPRINGTRAPOFFICELEAVING6.tim \
tim/office/animatronics/springtrap/SPRINGTRAPOFFICELEAVING7.tim \
tim/office/animatronics/springtrap/SPRINGTRAPOFFICELEAVING8.tim \
tim/office/animatronics/springtrap/running/1ST.tim \
tim/office/animatronics/springtrap/running/2ND.tim \
tim/office/animatronics/springtrap/running/3RD.tim \
tim/office/animatronics/springtrap/running/4TH.tim \
tim/office/animatronics/springtrap/running/5TH.tim \
tim/office/animatronics/springtrap/running/6TH.tim \
tim/office/animatronics/springtrap/running/7TH.tim \
tim/office/animatronics/springtrap/running/8TH.tim \
tim/office/animatronics/springtrap/running/9TH.tim \
tim/office/animatronics/springtrap/running/10TH.tim \
tim/office/animatronics/springtrap/running/11TH.tim \
tim/office/animatronics/springtrap/running/12TH.tim \
tim/office/panelsprite/PANEL0.tim \
tim/office/panelsprite/PANEL1.tim \
tim/office/panelsprite/PANEL2.tim \
tim/office/panelsprite/PANEL3.tim \
tim/office/panelsprite/PANEL4.tim \
tim/office/panelsprite/PANEL5.tim \
tim/camera/panel/static/100.tim \
tim/camera/panel/5.tim \
tim/camera/panel/4.tim \
tim/camera/panel/3.tim \
tim/camera/panel/2.tim \
tim/camera/panel/1.tim \
tim/camera/cams/vents/15/SPRINGTRAP15.tim \
tim/camera/cams/vents/1112/SPRINGTRAP11.tim \
tim/camera/cams/vents/1112/SPRINGTRAP12.tim \
tim/camera/cams/vents/1314/SPRINGTRAP13.tim \
tim/camera/cams/vents/1314/SPRINGTRAP14.tim \
tim/camera/cams/map/0910/SPRINGTRAP10.tim \
tim/camera/cams/map/0910/SPRINGTRAP9.tim \
tim/camera/cams/map/0708/SPRINGTRAP8.tim \
tim/camera/cams/map/0708/SPRINGTRAP7.tim \
tim/camera/cams/map/0506/SPRINGTRAP6.tim \
tim/camera/cams/map/0506/SPRINGTRAP5.tim \
tim/camera/cams/map/0304/SPRINGTRAP4.tim \
tim/camera/cams/map/0304/SPRINGTRAP3.tim \
tim/camera/cams/map/0102/SPRINGTRAP2.tim \
tim/camera/cams/map/0102/SPRINGTRAP1.tim \
tim/camera/panel/layout.tim \
tim/camera/panel/layoutvent.tim \
tim/office/FREDDYWANDERING.tim \
tim/office/mangle.tim \
tim/camera/verror.tim \
tim/camera/auerror.tim \
tim/Mpanel/AUDEVICE.tim \
tim/Mpanel/CAMSYS.tim \
tim/Mpanel/selection.tim \
tim/Mpanel/error.tim \
tim/Mpanel/EXIT.tim \
tim/Mpanel/Loadco.tim \
tim/Mpanel/MENU.tim \
tim/Mpanel/REBOOT.tim \
tim/Mpanel/RESTART.tim \
tim/Mpanel/VENTIL.tim \
tim/load.tim \
tim/fnt.tim \
tim/5am6/AM.tim \
tim/5am6/59.tim \
tim/5am6/6.tim \
tim/5am6/0.tim \
tim/titlemenu/nights/1ST.tim \
tim/titlemenu/nights/2ND.tim \
tim/titlemenu/nights/3RD.tim \
tim/titlemenu/nights/4TH.tim \
tim/titlemenu/nights/5TH.tim \
tim/titlemenu/nights/6TH.tim \
tim/titlemenu/nights/7TH.tim \
tim/titlemenu/lines/1.tim \
tim/titlemenu/lines/2.tim \
tim/titlemenu/lines/3.tim \
tim/titlemenu/lines/4.tim \
tim/titlemenu/lines/5.tim \
tim/titlemenu/SLTBUT.tim \
tim/titlemenu/NAME.tim \
tim/titlemenu/EXTRA.tim \
tim/titlemenu/NEWGAME.tim \
tim/titlemenu/LOADGAME.tim \
tim/titlemenu/WARNING.tim \
tim/titlemenu/star.tim \
tim/camera/LOL2.tim \
tim/camera/cams/vents/15/CAM.tim \
tim/screamer/BB/BBJUMP1.tim \
tim/screamer/BB/BBJUMP2.tim \
tim/screamer/BB/BBJUMP3.tim \
tim/screamer/BB/BBJUMP4.tim \
tim/screamer/BB/BBJUMP5.tim \
tim/screamer/BB/BBJUMP6.tim \
tim/screamer/BB/BBJUMP7.tim \
tim/screamer/BB/BBJUMP8.tim \
tim/screamer/BB/BBJUMP9.tim \
tim/screamer/Springtrap/1.tim \
tim/screamer/Springtrap/2.tim \
tim/screamer/Springtrap/3.tim \
tim/screamer/Springtrap/4.tim \
tim/screamer/Springtrap/5.tim \
tim/screamer/Springtrap/6.tim \
tim/screamer/Springtrap/7.tim \
tim/screamer/Springtrap/8.tim \
tim/screamer/Springtrap/9.tim \
tim/screamer/Springtrap/10.tim \
tim/screamer/Springtrap/11.tim \
tim/screamer/Springtrap/12.tim \
tim/screamer/Springtrap/13.tim \
tim/screamer/Springtrap2/1.tim \
tim/screamer/Springtrap2/2.tim \
tim/screamer/Springtrap2/3.tim \
tim/screamer/Springtrap2/4.tim \
tim/screamer/Springtrap2/5.tim \
tim/screamer/Springtrap2/6.tim \
tim/screamer/Springtrap2/7.tim \
tim/screamer/Springtrap2/8.tim \
tim/screamer/Springtrap2/9.tim \
tim/screamer/Springtrap2/10.tim \
tim/screamer/Springtrap2/11.tim \
tim/screamer/Springtrap2/12.tim \
tim/screamer/Chica/CHJUMP1.tim \
tim/screamer/Chica/CHJUMP2.tim \
tim/screamer/Chica/CHJUMP3.tim \
tim/screamer/Chica/CHJUMP4.tim \
tim/screamer/Chica/CHJUMP5.tim \
tim/screamer/Chica/CHJUMP6.tim \
tim/screamer/Freddy/FJUMP1.tim \
tim/screamer/Freddy/FJUMP2.tim \
tim/screamer/Freddy/FJUMP3.tim \
tim/screamer/Freddy/FJUMP4.tim \
tim/screamer/Freddy/FJUMP5.tim \
tim/screamer/Freddy/FJUMP6.tim \
tim/screamer/Freddy/FJUMP7.tim \
tim/screamer/Foxy/1.tim \
tim/screamer/Foxy/2.tim \
tim/screamer/Foxy/3.tim \
tim/screamer/Foxy/4.tim \
tim/screamer/Foxy/5.tim \
tim/screamer/Foxy/6.tim \
tim/screamer/Foxy/7.tim \
tim/screamer/Foxy/8.tim \
tim/screamer/Foxy/9.tim \
tim/screamer/Foxy/10.tim \
tim/screamer/Foxy/11.tim \
tim/camera/cams/animatronics/BBONCAM.tim \
tim/camera/cams/animatronics/MANGLE04.tim \
tim/camera/cams/animatronics/PUPPET.tim \
tim/camera/cams/animatronics/CHICA.tim \
tim/camera/TEST.tim \
tim/gameover/lines/1.tim \
tim/gameover/lines/2.tim \
tim/gameover/lines/3.tim \
tim/gameover/lines/4.tim \
tim/gameover/lines/5.tim \
tim/gameover/lines/6.tim \
tim/gameover/lines/7.tim \
tim/gameover/lines/8.tim \
tim/gameover/lines/9.tim \
tim/gameover/lines/10.tim \
vag/breathing.vag \
vag/sealingvent.vag \
vag/monitor_down.vag \
vag/monitor_up.vag \
vag/monitor_up_2.vag \
vag/officesound.vag \
vag/click.vag \
vag/screamer.vag \
vag/honk.vag \
vag/moving.vag \
vag/coin.vag \
vag/alarm.vag \
vag/mangle.vag \
vag/BB1.vag \
vag/BB2.vag \
vag/BB3.vag \
vag/ventquiet.vag \
vag/button.vag \
vag/consoleclosing.vag \
vag/consoleopening.vag \
vag/camambiance.vag \
vag/springtrapnear.vag \
vag/puppet.vag \

include ../common.mk 
